### ISSUE TITLE
Exit if Mqtt broker is unavailable

### ISSUE THREAD

**Issue by Papst** [micw/tibber-pulse-reader#18]
First: Great work. It works like a charm with one exception:

If my mqtt broker is offline (Restart,...) the timber pulse reader exits with a disconnected message.
Is it possible to continue and just try again to send the mqtt message with the next reading?

**Comment by micw** [comment]
That's mainly because I run it in docker/kubernetes. So when it's terminating, it is auto-restarted and I get a metric for it.

I do plan local persistence + auto-reconnect. But not directly within this project. I hav started to consolidate several of my projects for processing meter data into one project so that I have all new features available on all sources/destinations.

Have a look at https://github.com/micw/homedatabroker. Tibber is not yet integrated but when I find some time, I'll do it (currently the new project has only modbus/tcp ad source).

**Comment by Papst** [comment]
Ok, thanks. I will follow the development of your homedatabroker.

**Comment by Papst** [comment]
Ok, thanks. I will follow the development of your homedatabroker.

**Comment by micw** [comment]
Hello. I re-open this for discussion because I'm about to implement mqtt in homedatabroker these days. I will also port the tibber pulse reader code to it, so that users can switch over.

You wrote:
> Is it possible to continue and just try again to send the mqtt message with the next reading?

I will definitively implement re-connect. But what would be appropriate for metrics that are read while mqtt is offline. Since these mqtt messages usually have no timestamp, does it make sense to cache it and send it later? or should we just drop it until mqtt is available again?

**Comment by Clanchef** [comment]
Hello, I also appreciate this project and I use it since several months now. 
Recently mosquitto got updated automatically and tibber pulse reader lost connection ... in this case it would be better to drop the messages and wait until mqtt is back online again. I use the data for evcc and it just needs current data and no history.

**Comment by micw** [comment]
Hello,

nice, I also use it for EVCC (as well as for a dashboard). I will implement reconnect handling first and skip the history stuff on MQTT unless I have a use-case for it.

I write back here, as soon as I have MQTT and Tibber-Pulse integrated in homedatabroker.

**Comment by Papst** [comment]
I would also prefer to drop the messages until the mqtt broker is back online.

**Comment by micw** [comment]
@Papst @Clanchef I have integrated the pulse http reader into HomeDataBroker today. It works for me ;-)
Please give it a try. Feel free to open issues/discussions there if you have any questions. Documentation needs some work but there is an example config with a lot of examples.
